theme: jekyll-theme-cayman
title: Almost Obvious
description: "A site filled with deep dives into the world of math."
markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true
